pipeline {
    agent any
    environment {
        NODEJS_HOME = tool name: 'NodeJS' // Replace with your Node.js installation name in Jenkins
        PATH = "${NODEJS_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/atharvalavangare/project.git'
            }
        }
        stage('Build Angular App') {
            steps {
                dir('project/my-angular-app') { // Navigate to the Angular app directory
                    sh 'npm install'
                    sh 'npm run build --prod'
                }
            }
        }
        stage('Deploy to Nginx') {
            steps {
                sh 'sudo cp -r project/my-angular-app/dist/my-angular-app/* /var/www/angular-app/'
                sh 'sudo systemctl reload nginx'
            }
        }
    }
    triggers {
        // Trigger the pipeline on push to main branch
        githubPush()
    }
}
